/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import model.Entregador;
import model.Padaria;
import model.Embalador;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author laeciorodrigues
 */
public class TelarRealizarEntrega extends javax.swing.JFrame {

    /**
     * Creates new form TelarRealizarEntrega
     */
    Padaria padaria;
    public TelarRealizarEntrega(Padaria pad) {
        padaria = pad;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idPedido = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();
        btEntregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPedidos = new javax.swing.JList<>();

        jLabel3.setText("jLabel3");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REALIZAR ENTREGA");

        jLabel2.setText("ID do Pedido:");

        btVoltar.setText("VOLTAR");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btEntregar.setText("ENTREGAR");
        btEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntregarActionPerformed(evt);
            }
        });

        listaPedidos.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return padaria.getPedidos().size(); }
            public String getElementAt(int i) { return "ID: "+padaria.getPedidos().get(i).getID()+" -> "+padaria.getPedidos().get(i).getCliente().getNome()+" -> Latitude: "+padaria.getPedidos().get(i).getCliente().getLat()+" -> Longitude: "+padaria.getPedidos().get(i).getCliente().getLog(); }
        });
        jScrollPane2.setViewportView(listaPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(idPedido))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btVoltar)
                            .addGap(194, 194, 194)
                            .addComponent(btEntregar))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(idPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntregar)
                    .addComponent(btVoltar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        TelaPedidos pedidos = new TelaPedidos(padaria);
        pedidos.setLocationRelativeTo(null);
        pedidos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntregarActionPerformed
        int test = 0;
        String id = idPedido.getText();
        Entregador entre = new Entregador();
        Embalador embala = new Embalador();
        if(padaria.getPedidos()!=null){
            for(int i=0;i<padaria.getPedidos().size();i++){
                if(id.equals(String.valueOf(padaria.getPedidos().get(i).getID()))){
                    padaria.getPedidos().remove(i);
                    for(int p=0; p<padaria.getEmbaladores().size();p++){
                        padaria.getEmbaladores().get(i).setStatus(embala.aguardando());
                    }
                    for(int p=0; p<padaria.getEntregadores().size();p++){
                        padaria.getEntregadores().get(i).setStatus(entre.aguardando());
                    }
                    test=1;
                }
            }
        }
        if(test==1){
            JFrame frame = new JFrame ("Aviso!");
                JOptionPane.showMessageDialog(frame, "Entregue Com Sucesso!");
                
            TelarRealizarEntrega entrega = new TelarRealizarEntrega(padaria);
            entrega.setLocationRelativeTo(null);
            entrega.setVisible(true);
            dispose();
        }else{
            JFrame frame = new JFrame ("Aviso!");
                JOptionPane.showMessageDialog(frame, "Id não encontrado!");
                
            TelarRealizarEntrega entrega = new TelarRealizarEntrega(padaria);
            entrega.setLocationRelativeTo(null);
            entrega.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btEntregarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntregar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField idPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPedidos;
    // End of variables declaration//GEN-END:variables
}
