/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import model.Padaria;
import model.Embalador;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author laeciorodrigues
 */
public class TelaCadastroEmpacotador extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroEmpacotador
     */
    Padaria padaria;
    public TelaCadastroEmpacotador(Padaria pad) {
        padaria = pad;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeEmpacotador = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CADASTRAR EMPACOTADOR");

        jLabel3.setText("Nome:");

        nomeEmpacotador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpacotadorActionPerformed(evt);
            }
        });

        btVoltar.setText("VOLTAR");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btCadastrar.setText("CADASTRAR");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCadastrar)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(nomeEmpacotador, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeEmpacotador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(btCadastrar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
       TelaEmpacotador empacota = new TelaEmpacotador(padaria);
       empacota.setLocationRelativeTo(null);
       empacota.setVisible(true);
       dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void nomeEmpacotadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpacotadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpacotadorActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Embalador embalador = new Embalador();
        int ver = 0;
        try {
            if(nomeEmpacotador.getText().length()<3){
                ver = 1;
            }else{
                embalador.setNome(nomeEmpacotador.getText());
            }
        } catch (Exception e) {
            ver = 1;
            System.out.println("Erro: "+e);
        }
        if(ver == 0){
            int cont=0;
            if(padaria.getEmbaladores().size()!=0){
                int z;
                for(z=0;z<padaria.getEmbaladores().size();z++){
                    cont+=1;
                }
                if(padaria.getEmbaladores().get(z-1).getID() == cont){
                    cont+=1;
                }
            }
            embalador.setID(cont);
            embalador.setStatus(embalador.aguardando());
            padaria.getEmbaladores().add(embalador);
            JFrame frame = new JFrame ("Aviso!");
            JOptionPane.showMessageDialog (frame, "Cadastrado Com Sucesso!");
            TelaCadastroEmpacotador empacotador = new TelaCadastroEmpacotador(padaria);
            empacotador.setLocationRelativeTo(null);
            empacotador.setVisible(true);
            dispose();
        }else{
            JFrame frame = new JFrame ("Aviso!");
            JOptionPane.showMessageDialog (frame, "Preencha os dados corretamente!");
            TelaCadastroEmpacotador empacotador = new TelaCadastroEmpacotador(padaria);
            empacotador.setLocationRelativeTo(null);
            empacotador.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_btCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nomeEmpacotador;
    // End of variables declaration//GEN-END:variables
}
